export const queryKeys = {
  patients: ['patients'] as const,
  patient: (id: string) => ['patients', id] as const,
  bookings: ['bookings'] as const,
  booking: (id: string) => ['bookings', id] as const,
  doctors: ['doctors'] as const,
  doctor: (id: string) => ['doctors', id] as const,
  visits: ['visits'] as const,
  visit: (id: string) => ['visits', id] as const,
  services: ['services'] as const,
  service: (id: string) => ['services', id] as const,
  payments: ['payments'] as const,
  payment: (id: string) => ['payments', id] as const,
  notifications: ['notifications'] as const,
};
