name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🧠 SHORT SHA olish
      - name: Set image tag
        id: vars
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 🐳 Docker login
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u 10449 --password-stdin

      # 🔨 Build & push
      - name: Build and push Docker image
        run: |
          docker build -t 10449/zaxrodent_admin:${{ github.sha }} .
          docker push 10449/zaxrodent_admin:${{ github.sha }}

      # 🔐 Deploy
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        env:
          SHA_TAG: ${{ github.sha }}
        with:
          host: 116.203.244.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying commit: ${{ github.sha }}"

            docker pull 10449/zaxrodent_admin:${{ github.sha }}
            docker rm -f zaxrodent_admin || true

            docker run -d \
              --name zaxrodent_admin \
              -p 8070:8070 \
              10449/zaxrodent_admin:${{ github.sha }}